############################################################
#
# Управление светом в туалете
#
############################################################
- alias: Control lights in restroom
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.restroom_virtual_switch
      click_type: single
  action:
    service: switch.toggle
    entity_id: switch.restroom_switch

############################################################
#
# Управление светом в спальне
#
############################################################
- alias: Control lights in bedroom
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.bedroom_virtual_switch
      click_type: single
  action:
    service: switch.toggle
    entity_id: switch.bedroom_switch

############################################################
#
#  Управление светом в детской
#
############################################################
- alias: Control lights in kinderoom
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.childrensroom_virtual_switch
      click_type: single
  action:
    service: switch.toggle
    entity_id: switch.childrensroom_switch

############################################################
#
#  Управление светом в кухне
#
############################################################
- alias: Control lights in kitchen
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.kitchen_virtual_switch
      click_type: single
  action:
    service: switch.toggle
    entity_id: switch.kitchen_switch

############################################################
#
#  Включение света по датчику движения в коридоре
#
############################################################
- alias: Turn on hall light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion_sensor
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.hall_switch


############################################################
#
#  Выключение света через 3 минуты неактивности в коридоре
#
#########################################################
- alias: Turn off holl light 3 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion_sensor
    to: 'off'
    for:
      minutes: 3
  action:
    service: switch.turn_off
    entity_id: switch.hall_switch

############################################################
#
#  Выключить свет в туалете через 7 минут
#
############################################################
- alias: Turn off lights in restroom after 7 minutes
  trigger:
   - platform: state
     entity_id:
       - switch.restroom_switch
     from: 'off'
     to: 'on'
  action:
    - delay: '00:07:00'
    - service: switch.turn_off
      entity_id:
        - switch.restroom_switch

############################################################
#
#  Выключить свет в квартире
#
############################################################
- alias: Turn off lights in apartment
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.apartment_virtual_switch
      click_type: single
  action:
    - service: script.lights_turn_off

    - service: notify.alexa_media_rudenko_s_echo_dot
      data:
        message: "Goodbuy, Mike! See you soon!"
        data:
          type: tts

############################################################
#
#  Turn off lights in flat by bedroom switch
#
############################################################
- alias: Turn off lights in flat by bedroom switch
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.bedroom_virtual_switch
      click_type: double
  action:
    - service: script.lights_turn_off

############################################################
#
#  Выключить свет в зале через 40 минут
#
############################################################
- alias: Turn off lights in guestroom after 40 minutes
  trigger:
   - platform: state
     entity_id:
       - input_boolean.sleep_mode
     from: 'off'
     to: 'on'
  action:
    - delay: '00:40:00'
    - service: switch.turn_off
      entity_id: switch.guestroom_left_switch
    - service: switch.turn_off
      entity_id: switch.guestroom_right_switch
    - service: input_boolean.turn_off
      entity_id: input_boolean.sleep_mode

############################################################
#
#  Включить/Выключить стиральную машинку
#
############################################################
- alias: Control wash machine
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.washmachine_virtual_switch
      click_type: single
  action:
    service: switch.toggle
    entity_id: switch.washmachine_plug

############################################################
#
#  Включение света в столовой на полную мощность
#
############################################################
- alias: Turn on all dinner room lights
  trigger:
   - platform: state
     entity_id:
       - switch.diningroom_switch
     to: 'on'
  action:
    - delay: '00:00:01'
    - service: switch.turn_on
      entity_id:
        - switch.lamps_kitchen

############################################################
#
#  Включение колонок
#
############################################################
- alias: Turn speakers on
  trigger:
   - platform: state
     entity_id:
       - media_player.kitchen_lg_tv
     to: 'playing'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.logitech

############################################################
#
#  Выключение колонок
#
############################################################
- alias: Turn speakers off
  trigger:
   - platform: state
     entity_id:
       - media_player.kitchen_lg_tv
     to: 'off'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.logitech

############################################################
#
#  Выключение света в столовой (в начальное состояние)
#
############################################################
- alias: Turn off all dinner room lights
  trigger:
   - platform: state
     entity_id:
       - switch.diningroom_switch
     to: 'off'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.lamps_kitchen

############################################################
# Turn on/off Logitech Z906
############################################################
- alias: Turn on/off Logitech Z906
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.magic_cube
      action_type: tap_twice
  action:
    - service: script.logitech_z906_turn_on_off

############################################################
# Change volume Logitech Z906
############################################################
- alias: Change volume Logitech Z906
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.magic_cube
      action_type: rotate
  action:
  - service_template: >
        {% if trigger.event.data.action_value | float > 0 %}
          script.logitech_z906_volume_up
        {% else %}
          script.logitech_z906_volume_down
        {% endif %}

############################################################
#
#  Отправить сообщение в телеграмм при открытии двери
#
############################################################
- alias: Notify door open state
  trigger:
   - platform: state
     entity_id:
       - binary_sensor.hall_door_sensor
     from: 'off'
     to: 'on'
  action:
    - service: notify.telegram
      data:
        message: 'Входная дверь была окрыта!'


############################################################
#
#  Отправить сообщение в телеграмм при нажатии кнопки звонка
#
############################################################
- alias: Notify doorbell button click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.doorbell_virtual_switch
      click_type: single
  action:
    - service: notify.telegram
      data:
        message: 'Кто-то позвонил в звонок'
    - service: notify.alexa_media_rudenko_s_echo_dot
      data:
        message: "Knock-Knock. It's unexpexted guests! Don't open the door!"
        data:
          type: tts


############################################################
#
#  Уведомление о включении Home Assistant
#
############################################################
- alias: Home Assistant Notification
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.telegram
      data:
        message: "{{ '\U0001F384' }} Cервер запущен в {{ states('sensor.time') }}."
    - service: notify.alexa_media_rudenko_s_echo_dot
      data:
        message: "Home Assistant succesfully run"
        data:
          type: tts

############################################################
#
#  Уведомление об остановке Home Assistant
#
############################################################
- alias: Home Assistant Stop Notification
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: homeassistant_stop
  action:
    - service: notify.telegram
      data:
        message: "Home Assistant остановлен в {{ states('sensor.time') }}"
    - service: notify.alexa_media_rudenko_s_echo_dot
      data:
        message: "Home Assistant stopped"
        data:
          type: tts


############################################################
#  Sending daily Weather forecast to telegram
############################################################
- alias: system_weather_to_telegram
  initial_state: 'on'
  trigger:
    - platform: time
      at: '07:00:00'
    - platform: time
      at: '21:00:00'
  action:
    - service: notify.telegram
      data:
        message: |
            {%- set date = as_timestamp(now()) -%}
            {% set weekday_list = ['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'] %}
            {% set month_list = ['Января','Февраля','Марта','Апреля','Мая','Июня','Июля','Августа','Сентября','Октября','Ноября','Декабря'] %}
            {% set m_ok = date | timestamp_custom("%m") | int %}
            {% set wd_ok = date | timestamp_custom("%w") | int %}
            {% set weekday = weekday_list[wd_ok-1] %} 
            {% set month = month_list[m_ok-1] %} 
            {% set hour_num = now().hour | int %}
            {% if hour_num >=6 and hour_num <12 %} {{ "\U00002600" }}Доброе утро!
            {% elif hour_num>=12 and hour_num<17 %} {{ "\U0001f31e" }}Добрый день!
            {% elif hour_num>=17 and hour_num<22 %} {{ "\U0001f31d" }}Добрый вечер!
            {% else %} {{ "\U0001f31a" }}Доброй ночи!
            {% endif %}
            {%if hour_num < 17 and hour_num >= 0 %}
            Сегодня {{ weekday }}, {{ now().day|int }} {{ month_list[now().month-1] }}.
            {{ states('sensor.dark_sky_summary_0d') }}
            Максимальная температура {{states('sensor.dark_sky_daytime_high_temperature_0d')|round(0)}} °C.
            Минимальная температура {{states('sensor.dark_sky_overnight_low_temperature_0d')|round(0)}} °C.
            Вероятность осадков {{states('sensor.dark_sky_precip_probability_0d')|round(0)}}%. 
            {%if states('sensor.dark_sky_precip_probability_0d')|int > 0 %} Вид осадков - {% if states('sensor.dark_sky_precip_0d') == "snow" %}снег{% elif states('sensor.dark_sky_precip_0d') == "rain" %}дождь{% elif states('sensor.dark_sky_precip_0d') == "sleet" %}снег с дождем{% else %}неизвестно{% endif %}.
            {% endif %}
            {% endif %}
            {%if hour_num >= 17 and hour_num <= 23 %}
            Прогноз погоды на завтра - {{ states('sensor.dark_sky_summary_1d') }}
            Максимальная температура {{states('sensor.dark_sky_daytime_high_temperature_1d')|round(0)}} °C.
            Минимальная температура {{states('sensor.dark_sky_overnight_low_temperature_1d')|round(0)}} °C.
            Вероятность осадков {{states('sensor.dark_sky_precip_probability_1d')|round(0)}}%.
            {%if states('sensor.dark_sky_precip_probability_1d')|int > 0 %}Вид осадков - {% if states('sensor.dark_sky_precip_1d') == "snow" %}снег{% elif states('sensor.dark_sky_precip_1d') == "rain" %}дождь{% elif states('sensor.dark_sky_precip_1d') == "sleet" %}снег с дождем{% else %}неизвестно{% endif %}.
            {% endif %}
            {% endif %}
  
############################################################
#
#  Отправить сообщение в телеграмм при нажатии тестовой кнопки
#
############################################################
- alias: Notify test button click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.test_virtual_switch
      click_type: single
  action:
    - service: notify.alexa_media_rudenko_s_echo_dot
      data:
        data:
          type: tts
        message: "This is a weekly test of the announcing system."