homeassistant: !include homeassistant.yaml
default_config:

automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
xiaomi_aqara: !include xiaomi_aqara.yaml
telegram_bot: !include telegram_bot.yaml
notify: !include notify.yaml
input_boolean: !include input_boolean.yaml
zone: !include zones.yaml
media_player: !include media_players.yaml
http: !include http.yaml
webostv: !include webostv.yaml
homekit:

recorder:
  purge_keep_days: 3
  
      
input_datetime:
  cats_cleaning_date:
    name: Дата очистки туалета котов
    has_date: true
    has_time: false

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
    
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com

yandex_station:
  username: !secret yandex_username
  password: !secret yandex_password