####################
### IK Ping Pong ###
####################
- id: telegram-ik-ping-pong
  alias: 'telegram ping pong'
  hide_entity: true
  trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        data: '/cat_cleaned'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: >-
          Callback received from {{ trigger.event.data.from_first }}.
          Message id: {{ trigger.event.data.message.message_id }}.
          Data: {{ trigger.event.data.data }}
          {{now().strftime("%H:%M:%S %Y-%m-%d")}} Pong, Message from {{ trigger.event.data["user_id"] }}.
        show_alert: true

- id: 'testmessage'
  alias: "Telegram Test"
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    - service: notify.telegram
      data:
        message: 'pong'


############################################################ 
- alias: Clean camera Snapshots
  trigger:
  - minutes: /30
    platform: time_pattern
  condition: []
  action:
    - service: shell_command.clean_camera_snapshots
    
############################################################
#
#  Отправить сообщение в телеграмм со снимком с камеры
#
############################################################
- id: 'Camera message'
  alias: "Send camera photo"
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/camera'
  action:
    - service: notify.telegram
      data:
        title: Send an images
        message: "That's an example that sends an image."
        data:
          photo:
            - file: /share/motion/lastsnap.jpg
              caption: Фото с камеры


############################################################
#
#  Уведомление об очистке туалета котов
#
############################################################
- alias: Cat clean
  initial_state: 'on'
  trigger:
    - platform: time
      at: '08:30:00'
    - platform: time
      at: '20:00:00'
  condition:
    condition: template
    value_template: >
      {{ states('input_datetime.cats_cleaning_date') <= states('sensor.date') }}
  action:
    - service: notify.telegram
      data:
        message: "Почисть туалет у котов! {{ '\U0001F4A9' }}"
        data:
          inline_keyboard:
            - [["Уже почищено", "/cat_cleaned"], ["Отложить на завтра", "/cat_clean_tomorrow"]]
    - service: notify.alexa_media_rudenko_s_echo_dot
      data:
        message: "Hey! Wake up! It's time to clean cats toilet"
        data:
          type: tts

############################################################
#
#  Уведомление об очистке туалета котов
#
############################################################
- alias: Cats restroom cleaned
  initial_state: 'on'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/cat_cleaned'
  action:
    - service: notify.telegram
      data:
        message: "Следующий раз необходимо почистить туалет через 3 дня ({{ (as_timestamp(now()) + (3*24*3600)) |timestamp_custom('%d.%m.%Y') }})"

    - service: notify.alexa_media_rudenko_s_echo_dot
      data:
        message: "Oh! Finally! It's cleaned!"
        data:
          type: tts

    - service: input_datetime.set_datetime
      entity_id: input_datetime.cats_cleaning_date
      data_template:
        date: "{{ (as_timestamp(now()) + (3 * 24*3600)) |timestamp_custom('%Y-%m-%d') }}"


############################################################
#
#  Уведомление об отложенной уборке туалета котов до завтра
#
############################################################
- alias: Cats restroom will be cleaned tomorrow
  initial_state: 'on'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/cat_clean_tomorrow'
  action:
    - service: notify.telegram
      data:
        message: "Напоминание об уборке отложено до завтра ({{ (as_timestamp(now()) + (24*3600)) |timestamp_custom('%d.%m.%Y') }})"
    - service: input_datetime.set_datetime
      entity_id: input_datetime.cats_cleaning_date
      data_template:
        date: "{{ (as_timestamp(now()) + (24*3600)) |timestamp_custom('%Y-%m-%d') }}"
      